const number1 = 4;
const number2 = 7;
const product = number1 * number2;
console.log('product:', product);
console.log('typeof product:', typeof product);
const charge = 1;
const payment = 0;
const amountRemaining = charge - payment;
console.log('amountRemaining:', amountRemaining);
console.log('typeof amountRemaining:', typeof amountRemaining);
const tests = 30;
const assignments = 40;
const final = 50;
const grade = (tests + assignments + final) / 3;
console.log('grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Tev';
const lastName = 'Nicolas';
const fullName = firstName + ' ' + lastName;
console.log('fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 5;
const isAcidic = pH < 7;
console.log('isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const numberOfSoldiers = 22;
const isSparta = numberOfSoldiers === 300;
console.log('isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let nickName = fullName;
nickName += ' is the GOAT';
console.log('nickName:', nickName);
console.log('typeof nickName:', typeof nickName);
